# Generated by Django 4.1.5 on 2023-01-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet',
            new_name='Post',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author',
        ),
    ]
